var buttonColours=["red","blue","green","yellow"];
var gamePattern=[];    // To record the actaul patter generated by JS
var userClickedPattern=[]; // To record the pattern of user
var started=false;
var level;


// To Generate the next sequence for next level
function nextSequence()
{
  level=level+1;
  $("h1").text("Level "+level);
  var randomNumber=Math.floor(Math.random()*4);
  var randomChosenColour=buttonColours[randomNumber];
  gamePattern.push(randomChosenColour);
  currentButton="#"+randomChosenColour;
  $(currentButton).fadeOut(50).fadeIn(50);
  playSound(randomChosenColour);
  animatePress(randomChosenColour);
}

// When User clicks any Button
$("#green,#red,#yellow,#blue").click(function handler(){
   var userChosenColour=this.id;
   userClickedPattern.push(userChosenColour);
   playSound(userChosenColour);
   animatePress(userChosenColour);
   //console.log(userClickedPattern);
   checkAnswer(userClickedPattern.length-1); // To pass the index of the last element of User Clicked Pattern
});

function playSound(name)
{
  var audio = new Audio("sounds/"+name+".mp3");
  audio.play();
}

function animatePress(currentColour)
{
  $("#"+currentColour).addClass("pressed");
  setTimeout(function(){ $("#"+currentColour).removeClass("pressed"); }, 100);
}

$(document).keypress(function(event){
  if(started===false)
  {
   started=true;
   level=0;
	 nextSequence();
  }
});

function checkAnswer(currentLevel)
{
  var gameRecentIndex=gamePattern.length-1;
  var gameColour=gamePattern[currentLevel];
  var userColour=userClickedPattern[currentLevel];
  if(gameColour===userColour)
  {
    //console.log("Success");
    if(gamePattern.length===userClickedPattern.length)
    {
      userClickedPattern=[];
      setTimeout(function () {
        nextSequence();
      }, 1000);
    }
  }
  else
  {
    var audio = new Audio("sounds/wrong.mp3");
    audio.play();
    $("body").addClass("game-over");
    setTimeout(function(){ $("body").removeClass("game-over"); }, 200);
    $("h1").text("Game Over, Press Any Key to Restart");
    startover();
    //console.log("Fail");
  }
}

function startover()
{
  level=0;
  gamePattern=[];
  userClickedPattern=[];
  started=false;
}
